### ISSUE TITLE
Run error in ArchLinux

### ISSUE THREAD

**Issue by zxp19821005** [Alex313031/promethium#3]
**Bug description**
As titled.
*** Direct run
```
$ ./src/promethium-6.1.6.AppImage 
[1]    690358 trace trap (core dumped)  ./src/promethium-6.1.6.AppImage
```
*** Extracted and run
```
$ ./promethium
[1]    690875 trace trap (core dumped)  ./promethium
```
```
$ ./AppRun 
[1]    690945 trace trap (core dumped)  ./AppRun
```
*** Run through electron21
```
$ electron21 ./app.asar 
[691424:1113/184929.172949:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.InvalidArgs: 无此接口“org.freedesktop.portal.FileChooser”
[691424:1113/184929.173043:ERROR:select_file_dialog_linux_portal.cc(242)] Failed to read portal version property
(node:691424) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'whenReady')
    at /home/zxp-endeavouros/.cache/paru/clone/promethium-bin/src/squashfs-root/resources/app.asar/build/main.bundle.js:2:1011993
    at async A.onReady (/home/zxp-endeavouros/.cache/paru/clone/promethium-bin/src/squashfs-root/resources/app.asar/build/main.bundle.js:2:1011934)
    at async A.start (/home/zxp-endeavouros/.cache/paru/clone/promethium-bin/src/squashfs-root/resources/app.asar/build/main.bundle.js:2:1011883)
    at async /home/zxp-endeavouros/.cache/paru/clone/promethium-bin/src/squashfs-root/resources/app.asar/build/main.bundle.js:2:1024015
(Use `electron21 --trace-warnings ...` to show where the warning was created)
(node:691424) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```

**Details:**
 - Operating System: EndeavourOS
 - Promethium version: 6.1.6
 - Last known working version: unknown
 - DE: Cinnamon

**Comment by zxp19821005** [comment]
I've noticed that you used the third part Electron (https://github.com/Alex313031/promethium/blob/4e03fd90a56984b5ca518d2fb5b49a31e144c9e0/package.json#L83), will you please use the offical electron to try?

**Comment by s3nix-sys** [comment]
the way they have it set up, is if the actual electron is used it will break the project i have downloaded the code and tried it, the spacific version they have uses features that arent in vanilla electron
